### ISSUE TITLE
to_featureclass not unlocking layer

### ISSUE THREAD

**Issue by hildermesmedeiros** [Esri/arcgis-python-api#1364]
**Describe the bug**
When creating a new feature class with project opened it forces us to remove it to remove the layer lock. A simple remove and ctrl+z works.

**To Reproduce**
![image](https://user-images.githubusercontent.com/20046591/196753915-8a20fbc1-2b08-4c34-a991-57784cccccfa.png)
error:
![image](https://user-images.githubusercontent.com/20046591/196753993-d15f4712-48c7-4862-81e6-b8e0e550bc2c.png)

**Expected behavior**
I would like to see the layer lock free, once it's done editing.

**Platform (please complete the following information):**
 - OS: windows10
 - arcgispro: 2.8.7
 - arcgis default

**Comment by achapkowski** [comment]
@hildermesmedeiros this seems to be happening on the arcpy level.  FYI: @scw

**Comment by hildermesmedeiros** [comment]
We would have to follow the script till it calls arcpy.
But it is definitely the main suspect.

**Comment by scdub** [comment]
@hildermesmedeiros I can't reproduce this locally with a single GDB:

```python
import os
import pandas as pd

from arcgis.features import GeoAccessor
from pathlib import Path


p = r"C:\ArcGIS\Projects\notebook\notebook.gdb"


sdf = GeoAccessor.from_xy(pd.DataFrame({"col1":[1], "latitude":[-35.2], "longitude":[-54.3]}),
                          x_column='longitude', 'ycolumn='latitude')

res = sdf.spatial.to_featureclass(os.path.join(p, 'test_fc')
```

Shows me the layer without it being locked, but this is with a more recent Pro. It is possible it has been addressed with either 2.9 or 3.0.

**Comment by hildermesmedeiros** [comment]
Ok, so it is an arcgis problem, right?

The company I work with has a procidure of homolgation, I'm stuck with arcgispro 2.8, the only thing I can do is manage the envs but not the arcgispro version.
Comparing both I can see the culprint in my version.

![image](https://user-images.githubusercontent.com/20046591/196822895-9cf1aac0-9d88-43b5-a9c4-f81018c38a71.png)

Thanks, I will opt to change those lines, 814-815

**Comment by scdub** [comment]
You could also try setting `arcpy.env.addOutputsToMap = False` at the top of your script prior to see if it has any effect, or try the same in a locally modified copy of the script above.

**Comment by hildermesmedeiros** [comment]
Chaging to this fix the issue, thanks.
```         
array = np.array([], np.dtype(dtypes))
with arcpy.da.Editor(out_location) as editor:
    da.ExtendTable(fc, oidfld, array, join_dummy, append_only=False)
```

**Comment by hildermesmedeiros** [comment]
@achapkowski, I'm still facing this issue in another project. 
I think adding arcpy.ClearWorkspaceCache_management() might suffice. 
Any help in resolving it would be appreciated.

![Image](https://github.com/user-attachments/assets/dbd6e59f-aecc-4bd7-abf1-abdfe0e8a85e)
