### ISSUE TITLE
FeatureSet.from_geojson destroys MultiPolygons

### ISSUE THREAD

**Issue by gabeschine** [Esri/arcgis-python-api#1404]
**Describe the bug**
Loading GeoJSON into a `FeatureSet` loses information about `MultiPolygons`. Converting back to geojson exports a `Polygon` type instead of a `MultiPolygon`.

**To Reproduce**
```python
import json
from arcgis.features import FeatureSet

geojson_in = {'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'geometry': {'type': 'MultiPolygon',
    'coordinates': [[[[180.0, 40.0],
       [180.0, 50.0],
       [170.0, 50.0],
       [170.0, 40.0],
       [180.0, 40.0]]],
     [[[-170.0, 40.0],
       [-170.0, 50.0],
       [-180.0, 50.0],
       [-180.0, 40.0],
       [-170.0, 40.0]]]]}}]}

fs = FeatureSet.from_geojson(geojson_in)
geojson_out = json.loads(fs.to_geojson)

# geojson_out object is printed below
{'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[180.0, 40.0],
      [170.0, 40.0],
      [170.0, 50.0],
      [180.0, 50.0],
      [180.0, 40.0]],
     [[-170.0, 40.0],
      [-180.0, 40.0],
      [-180.0, 50.0],
      [-170.0, 50.0],
      [-170.0, 40.0]]]},
   'properties': {'OBJECTID': 1}}]}
```

**Expected behavior**
I expect a GeoJSON object that is correct. Notice how it outputs a `Polygon` object but with the polygon's rings collapsed. This has a completely different meaning.

**Platform (please complete the following information):**
 - OS: MacOS
 - Browser [e.g. chrome, safari]: n/a
 - Python API Version: 2.0.0

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by gabeschine** [comment]
Also of note is that retrieving one of these `FeatureSet`s from a `FeatureLayer` REST endpoint also outputs invalid GeoJSON when `.to_geojson` is called that lacks `MultiPolygons`. Asking for `f=geojson` output directly from the endpoint's `query` URL gives back _valid_ GeoJSON. This is how I first discovered the issue.

**Comment by nanaeaubry** [comment]
@gabeschine Hello, I am looking into this issue. 

Regarding your comment can you provide reproducible code of each case? This way I am testing the same way as you.

**Comment by nanaeaubry** [comment]
This issue has been fixed for the next release, thank you

**Comment by gabeschine** [comment]
Nice thanks @nanaeaubry !

Just for the sake of completeness, here's a code example for the problem that shows up when using the python `FeatureLayer` API:

```
from arcgis.features import FeatureLayer

FEATURE_LAYER_URL = "https://services.arcgis.com/jIL9msH9OI208GCb/ArcGIS/rest/services/California_Fire_Perimeters_1878_2019/FeatureServer/1"

layer = FeatureLayer(FEATURE_LAYER_URL)
where = f"FIRE_NAME='CZU LIGHTNING COMPLEX'"
results = layer.query(where, out_sr=4326)
print(results.to_geojson)

# Equivalent REST endpoint for geojson includes MultiPolygon as expected:
# https://services.arcgis.com/jIL9msH9OI208GCb/ArcGIS/rest/services/California_Fire_Perimeters_1878_2019/FeatureServer/1/query?where=FIRE_NAME%3D%27CZU+LIGHTNING+COMPLEX%27&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&relationParam=&returnGeodetic=false&outFields=&returnGeometry=true&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&defaultSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token=
```

Also: what is your release schedule? I'm wondering when I can expect a new version, and how I might track the release of this fix.

Cheers!

**Comment by nanaeaubry** [comment]
Awesome thanks! We will release in the second week of January 2023 version 2.1.0. 

Happy new year!

**Comment by EricSamson-Tract** [comment]
This appears to still be an issue. Using the sample code gabeschine posted, the python package seems to return improper geojson while the API returns it correctly.

**Comment by dnsohrabian** [comment]
@nanaeaubry  This bug is not fixed. MultiPolygons are not formatted correctly upon calling to_geojson on a FeatureSet.  Fairly certain that the problem is multipolygons are missing a level of nesting. Should I post as a separate issue? Or can you re-open this issue and get it fixed?

My evidence below:

```
# This is a neighborhoods layer we have on AGO
city_neighborhoods_item = gis.content.get("b2a2da54401a41e78dd71563f01f5273")
# Query and convert to geojson
hoods_gjson = city_neighborhoods_item.layers[0].query().to_geojson
```

Converting the geojson results to other formats in geopandas results in empty geometries for MultiPolygons.

Copy and paste resulting geojson string from `to_geojson` into a GeoJSON validator and it will tell you it is missing a level of array. 

**Adding an extra bracket at beginning and end of the coordinates array fixes the problem. When reading in other software (geopandas for example) the empty geometries are now valid MultiPolygon.**
