### ISSUE TITLE
ArcGIS API for Python SharingGroupManager Limitations?

### ISSUE THREAD

**Issue by theisenm12** [Esri/arcgis-python-api#2180]
I am trying to run a script that loops through my AGOL organizations documents (Microsoft Excel, Word and Powerpoint items) and return how many groups they are shared with in a table export. I have noticed that no matter how many groups an item is shared with, it caps at 5 groups in table. Does anyone know of any limitations on this function? Code below. 

```python
existing_item_id = 'xyz'

# Initialize an empty DataFrame to store item and group details
columns = ["Title", "Item Type", "Group Names", "Item Owner", "Number of groups", "Risk level","Item ID"]
items_df = pd.DataFrame(columns=columns)

# Get all unique item types in the organization, you can find a list of this online probably
item_types = ["Microsoft Excel", "Microsoft Powerpoint", "Microsoft Word"]

# Loop through each item type and fetch items
for item_type in item_types:
    print(f"Processing items of type: {item_type}")
    items = gis.content.search(query=f"type:\"{item_type}\"", max_items=5000)
   
    for item in items:
        # Use the SharingGroupManager to list groups the item belongs to
        groups = item.sharing.groups.list()
        group_names = [group['title'] for group in groups]
        
        # Count the number of groups
        num_groups = len(group_names)
       
        # Assign a risk level based on number of groups
        if num_groups >= 10:
            risk_level = "High"
        elif 5 <= num_groups < 10:
            risk_level = "Medium"
        else:
            risk_level = "Low"
    
        # Append item and group data to the DataFrame
        items_df = pd.concat([
            items_df,
            pd.DataFrame([{
                "Title": item.title,
                "Item Type": item_type,
                "Group Names": ", ".join(group_names), 
                "Item Owner": item.owner,
                "Number of groups": num_groups,
                "Risk Level": risk_level,
                "Item ID": item.id
            }])
        ], ignore_index=True)

# Save the DataFrame to a CSV file for further analysis
sharing_table = 'xyz'
items_df.to_csv(sharing_table, index=False)
print("Data export complete. File saved as 'xyz'.")

# Define the schema for the new table
fields = [
    {
        "name": "Title",
        "alias": "Title",
        "type": "esriFieldTypeString",
        "length": 255
    },
    {
        "name": "Item_Type",
        "alias": "Item Type",
        "type": "esriFieldTypeString",
        "length": 255
    },
    {
        "name": "Group_Names",
        "alias": "Group Names",
        "type": "esriFieldTypeString",
        "length": 5000  # Set the character limit to 5000
    },
    {
        "name": "Item_Owner",
        "alias": "Item Owner",
        "type": "esriFieldTypeString",
        "length": 255
    },
    {
        "name": "Number_of_groups",
        "alias": "Number of Groups",
        "type": "esriFieldTypeInteger"
    },
    {
        "name": "Risk_Level",
        "alias": "Risk Level",
        "type": "esriFieldTypeString",
        "length": 255
    },
    {
        "name": "Item_ID",
        "alias": "Item ID",
        "type": "esriFieldTypeString",
        "length": 255
    }
]

# Check if the Hosted table already exists in AGOL
existing_item = gis.content.search(query=f'id:{existing_item_id}')

try:
    if existing_item:
        # Get the existing Feature Layer Collection
        feature_layer_item = existing_item[0]
        feature_layer_collection = FeatureLayerCollection(feature_layer_item.url, gis)
        
        # Overwrite the existing feature layer with the new data
        feature_layer_collection.manager.overwrite(sharing_table)
        print("Updated existing feature layer in AGOL.")
    else:
        # Upload the CSV as a new feature layer
        item_properties = {
            'title': "xyz",
            'tags': "Item Management",
            'description': "xyz."
        }
        feature_layer_item = gis.content.add(item_properties, data=sharing_table, folder="Item_Management")
        
        # Publish the feature layer
        published_layer = feature_layer_item.publish(publish_parameters={"fields":fields})
        print("Uploaded new Hosted Table to AGOL.")

except Exception as e:
    print(f"An error occurred: {e}")

notification_users = ["xyz"]
subject = "xyz"
msgTxt = (f"xyz.")
                    
for user in notification_users:
    gis.users.send_notification([user], subject, msgTxt, type='email')    
    
print("Process completed.")
```
error:
The code runs successfully, but does not grab all the groups. I thought it might be a character limit issue but when running some debugging scripts, The for loop that cycles through each item and reads the shared groups was only picking up 5 groups for items that were shared with many more than that. I am wondering if I don't need to paginate somewhere in here, but I am not sure how I would go about that. 
```

**Expected behavior**
The code works great for all items and apps that have less than 5 groups shared. I am a novice programmer at best though and relish and tips or tricks. 

**Platform (please complete the following information):**
 - I am working in AGOL Notebook Python 3 Standard - 10.0 (the code also did not work properly in 11.0.)

Anywhere I have put xyz is to replace private information.

**Comment by nanaeaubry** [comment]
@theisenm12 Thanks for finding this! It is a bug. For now you can used the `shared_with` method instead in the Item class.

**Comment by theisenm12** [comment]
@nanaeaubry I found that this was also happening with other Item types as well. I will try to replace it with the shared_with function. 

Where would I replace "shared_with" in the script to theoretically make it work as a start? I thought that method was deprecated.

**Comment by nanaeaubry** [comment]
@theisenm12 
You can use it on each item: `item.shared_with` and then get the `groups` from that. It returns a dictionary.

https://developers.arcgis.com/python/latest/api-reference/arcgis.gis.toc.html#arcgis.gis.Item.shared_with

Deprecated means it will be removed in a later version, not that it doesn't work anymore. You can use it as a workaround for now and we will put a fix in for the other method

**Comment by theisenm12** [comment]
@nanaeaubry I replaced "groups = item.sharing.groups.list()" with "groups = item.shared_with()" and am getting the following error. Any thoughts? Should I use an older version than v10.0? 

/tmp/ipykernel_36/2597715065.py:22: DeprecatedWarning: shared_with is deprecated as of 2.3.0.1 and has be removed in 3.0.0. Use `Item.sharing` instead.
  groups = item.shared_with()

TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_36/2597715065.py in <cell line: 0>()
     20     for item in items:
     21         # Use the SharingGroupManager to list groups the item belongs to
---> 22         groups = item.shared_with()
     23         group_names = [group['title'] for group in groups]
     24 

TypeError: 'dict' object is not callable

**Comment by nanaeaubry** [comment]
@theisenm12 That's because it's a property: `item.shared_with`

**Comment by nanaeaubry** [comment]
@theisenm12 Hmm no with `shared_with` we are able to get more than 5 in our code. However, if you are not an admin it will only return groups you have access to.

**Comment by theisenm12** [comment]
@nanaeaubry Weird. I have a custom role but it essentially gives me the same permissions as admin. We also just tested the script with my coworker who is an admin and got the same results. Even using the following code snippet, I am still only getting 5 groups returned for specific item ID's. 

## access the content item as an item object
item = gis.content.get("xyz")

## item object -> SharingManager (.sharing)
## SharingManager -> SharingGroupManager (.groups)
## SharingGroupManager list() method
for group_obj in item.sharing.shared_with["groups"]:
    print(group_obj.title)

**Comment by nanaeaubry** [comment]
@theisenm12  We put a fix in for this issue and it will be in 2.4.1

For the shared_with the code is:
```
gis = GIS(profile="your_online_profile")
item = gis.content.get("item_id")
res = item.shared_with
res["groups"]
```

Closing since the issue has been fixed for next release

**Comment by theisenm12** [comment]
@nanaeaubry Hey Nanae, I went to try to update my script incorporating the fixed bug surrounding the item.sharing.groups.list() however I am still running into the same issue where I am only able to retrieve 5 groups max for each item. I wanted to post this here to let others know the issue is still recurring and to also seek help from you. Was the bug fixed in the update? 

Here is the code I am using:

# Loop through each item type and fetch items
for item_type in item_types:
    print(f"Processing items of type: {item_type}")
    items = gis.content.search(query=f"type:\"{item_type}\"", max_items=5000)
   
    for item in items:
        # Use the SharingGroupManager to list groups the item belongs to
        groups = item.sharing.groups.list()
        #groups = item.shared_with['groups']
        group_names = [group.title for group in groups]
        
        # Count the number of groups
        num_groups = len(group_names)
       
        # Assign a risk level based on number of groups
        if num_groups >= 10:
            risk_level = "High"
        elif 5 <= num_groups < 10:
            risk_level = "Medium"
        else:
            risk_level = "Low"
                
        # Check if the 'Item Description' contains the word "Purpose"
        if item.description and "Purpose" in item.description:
            metadata_status = "Complete"
        else:
            metadata_status = "Incomplete"
    
        # Append item and group data to the DataFrame
        items_df = pd.concat([
            items_df,
            pd.DataFrame([{
                "Title": item.title,
                "Item Type": item_type,
                "Group Names": ", ".join(group_names), 
                "Item Owner": item.owner,
                "Number of groups": num_groups,
                "Risk Level": risk_level,
                "Item ID": item.id,
                "Item Description": item.description,
                "Metadata Status": metadata_status,
                "Content Status": item.content_status,
            }])
        ], ignore_index=True)

Thanks a bunch, 

Matt

**Comment by whitacrej** [comment]
The SharingGroupsManager class does not include Partnered Collaboration groups, whereas, .shared_with['groups'] does. What is with that? If that is expected, what is the acceptable workaround? Thanks.

**Comment by achapkowski** [comment]
Partnered Collaborations are found off of the GIS.admin.partnered_collaboration property for ArcGIS Online.

**Comment by whitacrej** [comment]
@achapkowski I am not trying to access the information from the partnered_collaboration. I am trying access all the groups an item is shared with, including any groups involved in a Partnered Collaboration.

To clarify my initial comment, in my use case with the item I am working with, item.sharing.groups.list() does not include the Partnered Collaboration group it is shared with. However, item.shared_with['groups'] does include the Partnered Collaboration group. 

Is this a bug? Is this an intentional design? If it an intentional design, then what class/property would be appropriate to call to get the same information so I am not using a deprecated property? Seems like if I should use the new thing, it should have the exact same output as the old thing...but it doesn't.

The group in question is outside our org, so it is not a group that anyone in my organization 'owns'. I can't even access the .groups property of the partnered_collaboration class as it does not exist as a property when I create an instance of partnered_collaboration. Also, we are not the host of this Partnered Collaboration. But the content item clearly shows it is shared with the Partnered Collaboration group. Hope this all helps.

Update: I create a new issue for this behavior. See https://github.com/Esri/arcgis-python-api/issues/2397
