### ISSUE TITLE
Token Required - Error 499: When Attempting to Query Feature Layer (Arcgis 1.8.2)

### ISSUE THREAD

**Issue by PatrickFlynn** [Esri/arcgis-python-api#776]
Hello - please see below:

```
from arcgis.gis import GIS

gis = GIS("https://portalname.domain.com/webadapter_name", 
          client_id='1234_sample_client_id', 
          verify_cert=False)
```
This successfully opens up a browser and I login with IWA..

`print("Successfully logged in as: " + gis.properties.user.username)`

This returns a success message and I am able to explore my content in the Portal

```
l = gis.content.get('1234567_item_sample_id')
fl = l.layers[0]
```
I am able to get content (that is not shared/public) and use methods such as l.get_data()

`fl.query(where="1=1")`

This is where the failure occurs, and I am given an Exception "Token Required (Error Code: 499" 

Full failure below:

```
  File "<ipython-input-9-e7d33acb2760>", line 3, in <module>
    fl.query(where="1=1")

  File "C:\*****************\Anaconda3\lib\site-packages\arcgis\features\layer.py", line 1048, in query
    record_count = self._query(url, params, raw=as_raw)

  File "C:\*****************\Anaconda3\lib\site-packages\arcgis\features\layer.py", line 2048, in _query
    raise queryException

  File "C:\*****************\Anaconda3\lib\site-packages\arcgis\features\layer.py", line 2018, in _query
    postdata=params, token=self._token)

  File "C:\*****************\Anaconda3\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 710, in post
    force_bytes=kwargs.pop('force_bytes', False))

  File "C:\*****************\Anaconda3\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 505, in _handle_response
    self._handle_json_error(data['error'], errorcode)

  File "C:\*****************\Anaconda3\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 523, in _handle_json_error
    raise Exception(errormessage)

Exception: Token Required
(Error Code: 499)
```

**Comment by jrmatchett** [comment]
I've been experiencing the same issue with arcgis version 1.8.x. Digging through the code, it appears that several `FeatureLayer` methods, such as `query`, issue a call to a `Connection` object's `post` method, which requires a token to be specified. All those calls set the token parameter to `self._token`; however, `_token` is apparently not being set for a `FeatureLayer` object. The token does exist in the `FeatureLayer`'s `Connection` attribute (ie. `self._con.token`). I'm able to monkey patch `FeatureLayer` by adding a property that returns the token:
```
from arcgis.features import FeatureLayer
FeatureLayer._token = property(lambda self: self._con.token)
```
Querying then works properly.

**Comment by jrmatchett** [comment]
Digging into this a bit further, it seems the problem is that the `Connection` class' `generate_portal_server_token` method doesn't handle the case of OAUTH authentication using a client ID. I modified that method (located in file `arcgis/gis/_impl/_con/_connection.py`) to return the existing connection token:
```
def generate_portal_server_token(self, serverUrl, expiration=1440):
	"""generates a server token using Portal token"""
	if self._auth.lower() == 'oauth':
		return self.token
	elif self._auth.lower() in ["pki", 'iwa']:
	...
```

**Comment by rodrigoalmeida94** [comment]
I also encountered this issue and the suggestion you made @jrmatchett seems to fix the issue! Thanks a lot :) Any clue how we could try to get maintainers attention on this? Seems like a relatively important mishap.

**Comment by achapkowski** [comment]
We are working to address this issue.  Thank you for reporting this.

**Comment by achapkowski** [comment]
We fixed the issue already at 1.9.x, but I will include it in a 1.8.4 backport.

**Comment by rodrigoalmeida94** [comment]
Fantastic @achapkowski ! Thanks a lot 👍

**Comment by achapkowski** [comment]
@rodrigoalmeida94 thank you for letting us know about your issues and please continue to let us know if you encounter anything.

**Comment by spaceof7** [comment]
I get this error after upgrading from 1.8.1 to 1.8.5.  I can query layers In our organization but cannot query layers published by another organization.  downgrading to 1.8.1 allows me to seuccessfully query again.

Im trying to query the following layer as well as a couple other hosted by King County.

'https://gisdata.kingcounty.gov/arcgis/rest/services/OpenDataPortal/property__parcel_address_area/MapServer/1722'

**Comment by wwwdavid34** [comment]
I am still getting this error with 1.9.2, when trying to follow simple examples on ESRI page to query ImageLayer. The ad-hoc fix proposed by @jrmatchett above does not work. Any suggestions?

https://developers.arcgis.com/python/sample-notebooks/publishing-web-maps-and-web-scenes/

```
Python 3.8.12 (default, Oct 12 2021, 13:49:34)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from arcgis.gis import GIS
>>> import arcgis
>>> arcgis.__version__
'1.9.1'
>>> gis1=GIS()
>>> search_result = gis1.content.search("title:2020 USA Median AND owner:esri",
...                                    item_type = "Map Service", outside_org = True)
>>> median_age_item = search_result[1]
>>> print(median_age_item)
<Item title:"2020 USA Median Age" type:Map Image Layer owner:esri>
>>> median_age_item.layers
Token Required
(Error Code: 499)
>>> median_age_item._token=property(lambda self:self._con.token)
>>> median_age_item.layers
Token Required
(Error Code: 499)
```

**Comment by achapkowski** [comment]
Can you provide the item ID?

**Comment by krobine1** [comment]
This bug still exists using ArcGIS Pro 2.9.2 Python API when using Integrated Windows Authentication (IWA) to connect to the Portal. It exists in other requests including query requests to a Feature Layer. I've now tested it using queries, edits, attachment queries, downloads and deletes. I believe it exists with any request made to a Federated Service (both hosted and non-hosted). I also noticed that a token parameter was added to the query request. This works.  However, you cannot add a token parameter to any of the other requests I listed above. I worked around it by using the REST API to make my requests. This is a fairly significant task to rewrite any request to the Federated ArcGIS Server.  Please note that this bug does not exist when using a SAML authenticated AGOL/Portal. I'd be happy to show this to ESRI staff if needed. Thank you.

**Comment by krobine1** [comment]
OK, Will try that.  I'll respond back with my findings.

**Comment by krobine1** [comment]
I finally had a chance to test this using the 2.0.0 version of the API. The query request, and some of my attachment requests work great for IWA using the new API. The layer.edit_features is broken now. I think the bug is when you do this: from arcgis.features.geo import _is_geoenabled in your layer.py module. Nevertheless, when I wrap my edit_features in a try/catch, the catch never gets hit.  So not sure about that.  The other issue we're having now is that the 2.0.0 version of the API completely broke how we have been handing SAML requests. After making a SAML GIS connection, I can't even execute this line of code:  lyr_itm = portal.content.get(item_id) where portal is my GIS object and item_id is pointing to an item in my portal (works great is earlier versions of the Python API). I'll have to research this bug more to see if I can get it to work if I try a little different method of making my SAML GIS connection.
